# Generated by Django 5.1.6 on 2025-04-15 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0002_subscriptionplan_is_active_subscriptionplan_vendor_and_more'),
        ('Vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='Vendors.vendor'),
        ),
    ]
