# Generated by Django 5.1.6 on 2025-04-15 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0003_alter_subscriptionplan_vendor'),
        ('Vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='vendor',
            field=models.ForeignKey(default='H2Home', on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='Vendors.vendor'),
        ),
    ]
