# Generated by Django 5.1.6 on 2025-04-15 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0004_alter_subscriptionplan_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='vendor',
        ),
    ]
