# Generated by Django 5.1.6 on 2025-04-16 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0005_remove_subscriptionplan_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
