# Generated by Django 5.1.6 on 2025-03-18 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IOT', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='randomnumber',
            old_name='value',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='randomnumber',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
