# Generated by Django 5.1.6 on 2025-03-18 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendors', '0002_vendorvisit'),
        ('accounts', '0002_customerprofile_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='Vendors.vendor'),
        ),
    ]
