# Generated by Django 5.1.6 on 2025-03-29 21:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendors', '0003_vendor_website_alter_vendorvisit_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorvisit',
            name='visit_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
